### ISSUE TITLE
doesnt use right port

### ISSUE THREAD

**Issue by Mattis142** [efraimbart/OpenInWSA#2]
So I think this is a cool project, sadly it doesn't seemm to connect to the right port and therefore give an error instead, f.e it tries to connect to 127.0.0.1:5037, while my adb tells me that it is 127.0.0.1:58526 instead. I dont have a lot of knowledge on this so it might be totally easy to fix

**Comment by efraimbart** [comment]
I'm not sure where you see `5037`. See https://github.com/efraimbart/OpenInWSA/blob/main/OpenInWSA/Managers/WsaManager.cs#L32

**Comment by Mattis142** [comment]
Odd, because that's what the CMD window with the error showed

**Comment by efraimbart** [comment]
Can you post a screenshot please?

**Comment by Mattis142** [comment]
![image](https://user-images.githubusercontent.com/40364718/151620914-fc264a15-be52-479f-a3c1-016783babdce.png)

**Comment by efraimbart** [comment]
Looks like this is a problem with your adb daemon, not with adb connection to your device.

**Comment by Mattis142** [comment]
Do you have any suggestion to how I can fix this?

**Comment by efraimbart** [comment]
Does using adb directly work for you?

**Comment by efraimbart** [comment]
Closing this issue unless there is something further to discuss
